name: topics
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #core plugins
  connectivity_plus: ^2.3.6
  get_it: ^7.2.0
  dio: ^4.0.6
  equatable: ^2.0.3
  shared_preferences: ^2.0.15

#app plugins
  dartz: ^0.10.1
  pretty_dio_logger: ^1.1.1
  flutter_riverpod: ^1.0.4
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
